### ISSUE TITLE
Christmas 2024 update checklist

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/archetype#65]
- [x] new event progress bar asset
- [x] new event progress bar code
- [x] new gtl code
- [x] update info xml
- [x] new breed group / iv / gender / monster slot changes 
- [x] new breed window
- [x] social named gaps
